### ISSUE TITLE
Only one link of multiple links in the same line identified.

### ISSUE THREAD

**Issue by Miyuki-L** [mv5903/markdown-parser#1]
https://github.com/mv5903/markdown-parser/blob/55cb30dd4a5aee31b8a5761fde32f1e0fff1f9f4/MarkdownParse.java#L29-L39

Here is a failing Inducing input that does not get identified correctly
```
[text1](link1) and [text2](linke2)
```
Here is the symptom that is shows when running the test on MarkDownParser.java
<img width="663" alt="image" src="https://user-images.githubusercontent.com/59126064/168146036-99157703-1493-47f8-84d8-0b2fe0e073f4.png">

One suggestion to fix this issue is that have the program continue to look for a link until the line. So put the referenced lines in loop that keeps tracks of the which index at the line [,],(,) is found so that the next time around it looks for those [,],(,) after a certain index. Much like the this line in the original MarkdownParse repository we forked
https://github.com/nidhidhamnani/markdown-parser/blob/fc1622f444e81cc3d9decad29278c8484371843a/MarkdownParse.java#L29

**Comment by mv5903** [comment]
Fixed! Made each line have a nested while loop. This checks the remaining part of the string for the same characters.
